### ISSUE TITLE
Building the frontend-app-profile MFE results in pngquant/execa error

### ISSUE THREAD

**Issue by regisb** [overhangio/openedx-micromanager#1]
When running:

    make build APP=~/path/to/frontend-app-profile

I get the following error:

```
docker run --rm -it -e USERID=$(id -u) -v ~/projets/openedx/repos/frontend-app-profile:/app overhangio/openedx-mfe-build npm run build
Loading env from /app/env.sh

> @edx/frontend-app-profile@1.0.0-semantically-released build /app
> fedx-scripts webpack

clean-webpack-plugin: /app/dist has been removed.
Error parsing bundle asset "/app/dist/app.b2a1152d3d8880ae5394.js": no such file
Error parsing bundle asset "/app/dist/runtime.c27564d35578bafccaea.js": no such file
Error parsing bundle asset "/app/dist/vendors~app.35770c9b408e2b85f330.js": no such file

No bundles were parsed. Analyzer will show only original module sizes from stats file.

Webpack Bundle Analyzer saved report to /app/dist/report.html
Hash: ecc6c3133456a292f3f6
Version: webpack 4.41.1
Time: 21509ms
Built at: 10/16/2019 2:30:21 PM
 15 assets
Entrypoint app = runtime.c27564d35578bafccaea.js runtime.c27564d35578bafccaea.js.map vendors~app.35770c9b408e2b85f330.js vendors~app.35770c9b408e2b85f330.js.map app.b2a1152d3d8880ae5394.js app.b2a1152d3d8880ae5394.js.map
 [19] (webpack)/buildin/global.js 472 bytes {2} [built]
[143] ./node_modules/@edx/frontend-component-header/dist/index.js + 11 modules 59.7 KiB {2} [built]
      |    12 modules
[193] ./src/i18n/messages/ar.json 2.75 KiB {0} [built]
[194] ./src/i18n/messages/ca.json 2 bytes {0} [built]
[195] ./src/i18n/messages/es_419.json 2.85 KiB {0} [built]
[196] ./src/i18n/messages/fr.json 2.94 KiB {0} [built]
[197] ./src/i18n/messages/zh_CN.json 2.68 KiB {0} [built]
[198] ./src/i18n/messages/he.json 2 bytes {0} [built]
[199] ./src/i18n/messages/id.json 2 bytes {0} [built]
[200] ./src/i18n/messages/ko_kr.json 2 bytes {0} [built]
[201] ./src/i18n/messages/pl.json 2 bytes {0} [built]
[202] ./src/i18n/messages/pt_br.json 2 bytes {0} [built]
[455] ./src/index.scss 1.29 KiB {0} [built] [failed] [1 error]
[456] ./src/assets/favicon.ico 57 bytes {0} [built]
[458] ./src/index.jsx + 49 modules 194 KiB {0} [built]
      | ./src/index.jsx 1.34 KiB [built]
      | ./src/i18n/index.jsx 987 bytes [built]
      | ./src/profile/index.js 277 bytes [built]
      | ./src/store/index.js 272 bytes [built]
      | ./src/profile/data/reducers.js 5.26 KiB [built]
      | ./src/profile/data/sagas.js 11.6 KiB [built]
      | ./src/profile/ProfilePage.messages.jsx 443 bytes [built]
      | ./src/profile/ProfilePage.jsx 15.4 KiB [built]
      | ./src/profile/NotFoundPage.jsx 656 bytes [built]
      | ./src/store/configureStore.prod.js 584 bytes [built]
      | ./src/store/configureStore.dev.js 826 bytes [built]
      | ./src/profile/data/actions.js 4.06 KiB [built]
      | ./src/profile/data/selectors.js 14.2 KiB [built]
      | ./src/profile/data/services.js 11.4 KiB [built]
      | ./src/profile/forms/ProfileAvatar.jsx 7.43 KiB [built]
      |     + 35 hidden modules
    + 600 hidden modules

WARNING in ./node_modules/react-responsive/dist/react-responsive.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file 'webpack:///dist/react-responsive.js': Error: Can't resolve './webpack:///dist/react-responsive.js' in '/app/node_modules/react-responsive/dist'
 @ ./node_modules/@edx/frontend-component-header/dist/SiteHeader.js 2:0-42 61:71-81 63:68-78
 @ ./node_modules/@edx/frontend-component-header/dist/index.js
 @ ./src/index.jsx

ERROR in ./node_modules/@edx/frontend-component-footer/dist/edx-openedx-logo-tag.png
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error
    at afterWriteDispatched (internal/stream_base_commons.js:150:25)
    at writeGeneric (internal/stream_base_commons.js:141:3)
    at Socket._writeGeneric (net.js:770:11)
    at Socket._write (net.js:782:8)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Socket.Writable.write (_stream_writable.js:305:11)
    at Socket.Writable.end (_stream_writable.js:594:10)
    at Socket.end (net.js:574:31)
    at handleInput (/app/node_modules/imagemin-pngquant/node_modules/execa/index.js:89:17)
    at module.exports (/app/node_modules/imagemin-pngquant/node_modules/execa/index.js:309:2)
    at /app/node_modules/imagemin-pngquant/index.js:52:13
 @ ./node_modules/@edx/frontend-component-footer/dist/components/Footer.js 18:48-86
 @ ./node_modules/@edx/frontend-component-footer/dist/index.js
 @ ./src/index.jsx

ERROR in ./src/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error
    at afterWriteDispatched (internal/stream_base_commons.js:150:25)
    at writeGeneric (internal/stream_base_commons.js:141:3)
    at Socket._writeGeneric (net.js:770:11)
    at Socket._write (net.js:782:8)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Socket.Writable.write (_stream_writable.js:305:11)
    at Socket.Writable.end (_stream_writable.js:594:10)
    at Socket.end (net.js:574:31)
    at handleInput (/app/node_modules/imagemin-pngquant/node_modules/execa/index.js:89:17)
    at module.exports (/app/node_modules/imagemin-pngquant/node_modules/execa/index.js:309:2)
    at /app/node_modules/imagemin-pngquant/index.js:52:13
    at /app/node_modules/webpack/lib/NormalModule.js:316:20
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /app/node_modules/image-webpack-loader/index.js:87:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/index.jsx 11:0-22
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./public/index.html 712 bytes {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!node_modules/resolve-url-loader/index.js!node_modules/sass-loader/lib/loader.js??ref--6-4!src/index.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js??ref--6-4!./src/index.scss 859 KiB {0} [built]
    [9] ./src/profile/assets/dot-pattern-light.png 804 bytes {0} [built] [failed] [1 error]
        + 8 hidden modules
    
    ERROR in ./src/profile/assets/dot-pattern-light.png
    Module build failed (from ./node_modules/image-webpack-loader/index.js):
    Error
        at afterWriteDispatched (internal/stream_base_commons.js:150:25)
        at writeGeneric (internal/stream_base_commons.js:141:3)
        at Socket._writeGeneric (net.js:770:11)
        at Socket._write (net.js:782:8)
        at doWrite (_stream_writable.js:431:12)
        at writeOrBuffer (_stream_writable.js:415:5)
        at Socket.Writable.write (_stream_writable.js:305:11)
        at Socket.Writable.end (_stream_writable.js:594:10)
        at Socket.end (net.js:574:31)
        at handleInput (/app/node_modules/imagemin-pngquant/node_modules/execa/index.js:89:17)
        at module.exports (/app/node_modules/imagemin-pngquant/node_modules/execa/index.js:309:2)
        at /app/node_modules/imagemin-pngquant/index.js:52:13
     @ ./src/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js??ref--6-4!./src/index.scss) 11:38-87
```

(insert here some angry python dev rumblings about unreadable node stacktraces)

It seems to me that the build fails because of a missing package inside the Alpine docker image, but I can't figure out which one. I tried installing the following packages, without success: bash pngquant optipng lcms2-dev autoconf automake build-base libpng-dev (as suggested [here](https://github.com/imagemin/pngquant-bin/issues/65#issuecomment-374965562).

I don't quite know how to debug this further, as I have very little knowledge and understanding about nodejs development. Maybe you can help @abutterworth @davidjoy? To reproduce, just follow the steps from the README, with APP pointing to your frontend-app-profile repo.

**Comment by davidjoy** [comment]
Crossposting from Slack: 

 I recall that node-sass (https://github.com/sass/node-sass) is not pure JavaScript and has a dependency on LibSass, which may have its own deps.  That’s the first thing that comes to mind.

Given that part of that stack trace is CSS-related, that might be a good place to start.

Also, I can say that this warning can safely be ignored:

```
WARNING in ./node_modules/react-responsive/dist/react-responsive.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file 'webpack:///dist/react-responsive.js': Error: Can't resolve './webpack:///dist/react-responsive.js' in '/app/node_modules/react-responsive/dist'
 @ ./node_modules/@edx/frontend-component-header/dist/SiteHeader.js 2:0-42 61:71-81 63:68-78
 @ ./node_modules/@edx/frontend-component-header/dist/index.js
 @ ./src/index.jsx
```

**Comment by regisb** [comment]
Turns out, pngquant was the only package missing, but I should have installed it prior to running `make install`. Thanks for your help @davidjoy @abutterworth!
